name: echoman

services:  
  server:
    build:
      context: ./.docker/go
      dockerfile: Dockerfile
    container_name: server.local
    networks:
      echoman:
        ipv4_address: 10.0.3.95
        ipv6_address: fde4:db8::0395
    privileged: true
    restart: always
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "0" # enable
    tty: true
    volumes:
      - type: bind
        source: ./server
        target: /go/src/github.com/GotoRen/echoman/server
        bind:
          create_host_path: true
    working_dir: /go/src/github.com/GotoRen/echoman/server
 
  client:
    build:
      context: ./.docker/go
      dockerfile: Dockerfile
    container_name: client.local
    networks:
      echoman:
        ipv4_address: 10.0.3.96
        ipv6_address: fde4:db8::0396
    privileged: true
    restart: always
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "0" # enable
    tty: true
    volumes:
      - type: bind
        source: ./client
        target: /go/src/github.com/GotoRen/echoman/client
        bind:
          create_host_path: true
    working_dir: /go/src/github.com/GotoRen/echoman/client

networks:
  echoman:
    name: echoman_link
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.3.0/22
        - subnet: fde4:db8::/8
    enable_ipv6: true
